name    'jfryman-irc'
version '0.0.1'
source 'http://github.com/jfryman/puppet-irc'
author 'James Fryman'
license 'Apache License Version 2.0'
summary 'Puppet irc server management module'
description 'This module can be used for basic ircd Management'
project_page 'http://github.com/jfryman/puppet-irc'

dependency 'puppetlabs/stdlib', '>= 0.1.6'
